services:
  server:
    build: .
    ports:
      - "3000:3000"
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - ./config/influxdb/data:/var/lib/influxdb2
      - ./config/influxdb/config:/etc/influxdb2
    ports:
      - 8086:8086
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - ./config/mosquitto/:/mosquitto
    ports:
      - 1883:1883
      - 9001:9001
  telegraf:
    image: telegraf:latest
    container_name: telegraf
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - ./config/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    ports:
      - 8125:8125
      - 8092:8092
      - 8094:8094